/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 17 00:31:54 GMT 2019
 */

package com.desafio.desafiob2w.service.exception;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ResourceNotFoundException_ESTest extends ResourceNotFoundException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResourceNotFoundException resourceNotFoundException0 = new ResourceNotFoundException("$q|'nO/,)&*h5Yjq");
  }
}
